### PR TITLE
Add button to copy steam guard mobile code.

### PR DESCRIPTION
**Pull request by TheEnderOfficial**

### CODE REVIEW

**Comment by TheEnderOfficial** [comment]
SS
image

**Comment by TheEnderOfficial** [comment]
I found a bug, if you add sharedSecret with edit button is not showing, i`m going fix it, evening (i`m from Russia, GMT+3, sorry for my English)

**Comment by TheEnderOfficial** [comment]
If remove it, copy button removing.

**Review by dumbasPL — COMMENTED** [review]
TODO: update change log

**Comment by dumbasPL** [comment]
will merge this later (If i don't forget :sweat_smile:)

**Comment by TheEnderOfficial** [comment]
> I found a bug, if you add sharedSecret with edit button is not showing, i'm going fix it, evening (i'm from Russia, GMT+3, sorry for my English)

i tried to fix this, but i can`t maybe you can fix it

**Comment by dumbasPL** [comment]
> > I found a bug, if you add sharedSecret with edit button is not showing, i'm going fix it, evening (i'm from Russia, GMT+3, sorry for my English)
> 
> i tried to fix this, but i can`t maybe you can fix it

I'm not sure if I understand you. Can you record a video showing it? Everything is working fine for me.

**Review by dumbasPL — APPROVED** [review]
Seems good to me

**Pull request merged**
